import 'package:freezed_annotation/freezed_annotation.dart';

part 'stripe_receipt.freezed.dart';       // generated by freezed
part 'stripe_receipt.g.dart';             // generated by json_serializable

// @freezed
// abstract class StripeReceipt with _$StripeReceipt {
//   const factory StripeReceipt({
//     @JsonKey(name: 'createTime') required DateTime createTime,
//     @JsonKey(name: 'client_stripe_customer_id') required String clientStripeCustomerId,
//     @JsonKey(name: 'client_payment_method_id') required String clientPaymentMethodId,
//     @JsonKey(name: 'client_user_id') required String clientUserId,
//     @JsonKey(name: 'vendor_stripe_account_id') required String vendorStripeAccountId,
//     @JsonKey(name: 'vendor_user_id') required String vendorUserId,
//     @JsonKey(name: 'payment_amount_cents') required int paymentAmountCents,
//     @JsonKey(name: 'payment_intent_id') required String paymentIntentId,
//     @JsonKey(name: 'service_id') required String serviceId,
//     @JsonKey(name: 'booking_id') required String bookingId,
//     @JsonKey(name: 'service_name') required String serviceName,
//     @JsonKey(name: 'vendor_business_name') required String vendorBusinessName
//   }) = _StripeReceipt;
//
//   factory StripeReceipt.fromJson(Map<String, dynamic> json) => _$StripeReceiptFromJson(json);
// }

@freezed
abstract class StripeReceipt with _$StripeReceipt {
  const factory StripeReceipt({
    required DateTime createTime,
    required String clientStripeCustomerId,
    required String clientPaymentMethodId,
    required String clientUserId,
    required String vendorStripeAccountId,
    required String vendorUserId,
    required int paymentAmountCents,
    required String paymentIntentId,
    required String serviceId,
    required String bookingId,
    required String serviceName,
    required String vendorBusinessName
  }) = _StripeReceipt;

  factory StripeReceipt.fromJson(Map<String, dynamic> json) => _$StripeReceiptFromJson(json);
}



