import 'package:freezed_annotation/freezed_annotation.dart';

part 'stripe_refund.freezed.dart';       // generated by freezed
part 'stripe_refund.g.dart';             // generated by json_serializable

// @freezed
// abstract class StripeRefund with _$StripeRefund {
//   const factory StripeRefund({
//     @JsonKey(name: 'booking_id') required String bookingId,
//     @JsonKey(name: 'client_user_id') required String clientUserId,
//     @JsonKey(name: 'createTime') required DateTime createTime,
//     @JsonKey(name: 'payment_amount_original_cents') required int paymentAmountCents,
//     @JsonKey(name: 'payment_intent_id') required String paymentIntentId,
//     @JsonKey(name: 'refund_amount_cents') required int refundAmountCents,
//     @JsonKey(name: 'refund_charge_id') required String refundChargeId,
//     @JsonKey(name: 'refund_id') required String refundId,
//     @JsonKey(name: 'refund_initiator') required String refundInitiator,
//     @JsonKey(name: 'service_id') required String serviceId,
//     @JsonKey(name: 'service_name') required String serviceName,
//     @JsonKey(name: 'transfer_reversal') required String transferReversal,
//     @JsonKey(name: 'vendor_business_name') required String vendorBusinessName,
//     @JsonKey(name: 'vendor_user_id') required String vendorUserId,
//   }) = _StripeRefund;
//
//   factory StripeRefund.fromJson(Map<String, dynamic> json) => _$StripeRefundFromJson(json);
// }

@freezed
abstract class StripeRefund with _$StripeRefund {
  const factory StripeRefund({
    required String bookingId,
    required String clientUserId,
    required DateTime createTime,
    required int paymentAmountCents,
    required String paymentIntentId,
    required int refundAmountCents,
    required String refundChargeId,
    required String refundId,
    required String refundInitiator,
    required String serviceId,
    required String serviceName,
    required String transferReversal,
    required String vendorBusinessName,
    required String vendorUserId,
  }) = _StripeRefund;

  factory StripeRefund.fromJson(Map<String, dynamic> json) => _$StripeRefundFromJson(json);
}