

/// make sure seed services uses these
List<String> serviceCategories = [
  "Any",
  "Music",
  "Venues",
  "Catering",
  "Bartending",
  "Photography",
  "Event Planning",
  "Entertainment",
  "Balloon Art",
  "Face Painting",
  "Party Rentals",
  "Handymen",
  "Painting",
  "General Contracting",
  "Pest Control",
  "Appliance Repair",
  "Plumbing",
  "Cleaning",
  "Car Wash",
  "Laundry",
  "Gardening",
  "Landscaping",
  "Carpentry",
  "Electrical",
  "HVAC",
  "Pressure Washing",
  "Hair",
  "Beauty",
  "Massage",
  "Tanning",
  "Spa",
  "Yoga",
  "Pilates",
  "Dance",
  "Fitness",
  "Wellness",
  "Baking",
  "Cake Decorating",
  "Floral Design",
  "Food Truck",
  "Grocery",
  "Home Decor",
  "Home Improvement",
  "Pet Care",
  "Tutors",
  "Lessons",
  "Travel",
  "Wedding",
  "Personal Assistance",
  "Moving",
  "Professional Services",
  "Transportation",
  "Health",
  "Other",
];

final List<String> serviceSiteOptions = ['on-site', 'client-site', 'delivery', 'remote'];

final List<int> serviceDistanceOptions = [5, 25, 100, 750];