import 'package:freezed_annotation/freezed_annotation.dart';

part 'services.freezed.dart';       // generated by freezed
part 'services.g.dart';             // generated by json_serializable

@freezed
abstract class ServiceOffered with _$ServiceOffered {
  const factory ServiceOffered({
    String? address,
    required String category,
    required DateTime createTime,
    required String description,
    String? email,
    required String featureImageId,
     String? geoHash,
    required List imageIds,
    required List<String> keywords,
     Map<String, dynamic>? location,
    required String name,
     String? phoneNumber,
    required int priceCents,
     int? radius,
     double? rating,
      int? ratingCount,
    required String serviceId,
     required String site,  /// on-site, client-site, remote, delivery
     int? timeLength,
    required String vendorUserId,
    required String vendorBusinessName,
    required String vendorUserName,
  }) = _ServiceOffered;

  factory ServiceOffered.fromJson(Map<String, dynamic> json) => _$ServiceOfferedFromJson(json);

}