// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG_Wtv_RLJPWA76oYu2LiX8gv02pToz6o',
    appId: '1:631708018726:web:cc0dcc1fcf444ef4801ee7',
    messagingSenderId: '631708018726',
    projectId: 'connectme-app-11465',
    authDomain: 'connectme-app-11465.firebaseapp.com',
    storageBucket: 'connectme-app-11465.firebasestorage.app',
    measurementId: 'G-3TC7GYMPH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEt2bR4KINoLg_EdeBhnb-9EY8q3xifIg',
    appId: '1:631708018726:android:78435308c917602b801ee7',
    messagingSenderId: '631708018726',
    projectId: 'connectme-app-11465',
    storageBucket: 'connectme-app-11465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBodLnmSj1oNDP0n-5-6DuX1C33o8Inq_k',
    appId: '1:631708018726:ios:5747162d01b96983801ee7',
    messagingSenderId: '631708018726',
    projectId: 'connectme-app-11465',
    storageBucket: 'connectme-app-11465.firebasestorage.app',
    iosBundleId: 'com.example.connectmeApp',
  );
}
