import 'package:freezed_annotation/freezed_annotation.dart';

part 'message.freezed.dart';       // generated by freezed
part 'message.g.dart';

@freezed
abstract class Message with _$Message{
  const factory Message({
    required String messageId,
    required String receiverId,
    required String senderName,
    required String senderId,
    required String text,
    required String threadId,
    required DateTime timestamp
  }) = _Message;

  factory Message.fromJson(Map<String, dynamic> json) => _$MessageFromJson(json);
}