import 'package:freezed_annotation/freezed_annotation.dart';

part 'message_thread.freezed.dart';       // generated by freezed
part 'message_thread.g.dart';

@freezed
abstract class MessageThread with _$MessageThread{
  const factory MessageThread({
    required String threadId,
    required String lastMessage,
    required DateTime lastUpdated,
    required List<String> userIds,
    required List<String> userNames
  }) = _MessageThread;

  factory MessageThread.fromJson(Map<String, dynamic> json) => _$MessageThreadFromJson(json);
}

