import 'package:freezed_annotation/freezed_annotation.dart';

part 'user_message_thread.freezed.dart';       // generated by freezed
part 'user_message_thread.g.dart';

@freezed
abstract class UserMessageThread with _$UserMessageThread{
  const factory UserMessageThread({
    required String lastMessage,
    required DateTime lastUpdated,
    required String otherUserId,
    required String otherUserName,
    required String threadId,
    List? unread,
    List? wantBlock,
  }) = _UserMessageThread;

  factory UserMessageThread.fromJson(Map<String, dynamic> json) => _$UserMessageThreadFromJson(json);
}