import 'package:freezed_annotation/freezed_annotation.dart';

part 'booking.freezed.dart';       // generated by freezed
part 'booking.g.dart';             // generated by json_serializable

@freezed
abstract class Booking with _$Booking {
  const factory Booking({
    String? address, /// null for remote
    required String bookingId,
    required DateTime bookingTime,
    required String clientUserId,
    required String clientUserName,
    required DateTime createTime,
    required int priceCents,
    required String serviceId,
    required String serviceName,
    required String site, /// on-site, client-site, remote, delivery
    required String status, /// pending, confirmed, complete
    required int timeLength,
    required String vendorBusinessName,
    required String vendorUserId,
    required String vendorUserName,
  }) = _Booking;
  factory Booking.fromJson(Map<String, dynamic> json) => _$BookingFromJson(json);
}